sourcefuse/loopback4-audit-log

- .eslintignore
- package-lock.json
- package.json
- src/.eslintignore
- src/mixins/audit.mixin.ts
Upgraded dependencies using `lb4 update`
Lint fixes
> upgraded dependencies, lint fixes

- package-lock.json
- package.json
Description
Updated versions of All Loopback packages.
Type of change
> fix(version): updated version for all loopback packages

- package-lock.json
- package.json
- src/__tests__/acceptance/audit.mixin.acceptance.ts
- src/__tests__/acceptance/fixtures/datasources/audit.datasource.ts
- src/__tests__/acceptance/fixtures/datasources/test.datasource.ts
- src/__tests__/acceptance/fixtures/models/audit.model.ts
- src/__tests__/acceptance/fixtures/models/test.model.ts
- src/__tests__/acceptance/fixtures/repositories/audit-error.repository.ts
- src/__tests__/acceptance/fixtures/repositories/audit.repository.ts
- src/__tests__/acceptance/fixtures/repositories/test.repository.ts
- src/__tests__/unit/audit.mixin.unit.ts
- src/__tests__/unit/fixtures/mockClass.ts
- src/__tests__/unit/fixtures/mockData.ts
- src/__tests__/unit/fixtures/mockModel.ts
GH-10
Added Acceptance and Unit Test cases for AuditRepositoyMixin
> test(core): add tests for AuditRepositoryMixin

- package.json
GH-0
updated version of the lb4 dependencies to the latest.
> fix(auditlog): version update

- package-lock.json
GH-0
##Description
updated version of the lb4 dependencies to the latest.
##Checklist:
> fix(chore): package lock version update

- .eslintrc.js
- package-lock.json
- package.json
GH-0
Updated audit-log to latest dependencies.
> fix(chore): update audit-log to latest dependencies

- .cz-config.js
- package-lock.json
- package.json
- src/__tests__/acceptance/audit.mixin.acceptance.ts
- src/__tests__/unit/audit.mixin.unit.ts
updated all dependencies. Used node v16.0.0 (npm v7.10.0)
GH-22
> chore(deps): update all dependencies

- .github/PULL_REQUEST_TEMPLATE.md
- package-lock.json
- src/mixins/audit.mixin.ts
GH-33
Reduced the 3 DB calls in updateById to 2 calls 
this will have a really good performance impact as it will improve the latency
> fix(core): reduce the updateById 3 DB calls to 2

- package-lock.json
- package.json
remove all curent vulnerability of loopback4-audit-log
GH-45
Fixes #45 
> fix(chore): remove all current vulnerability of loopback4-audit-log

- package-lock.json
- package.json
- Updates the `@loopback/repository` package version to the latest one.
Fixes #55
> chore(deps): update `@loopback/repository` version

- package-lock.json
- package.json
- src/__tests__/acceptance/audit.mixin.acceptance.ts
update package dependencies
BREAKING CHANGE:
remove support for node 16
GH-85
1. remove support for node 16
2. update package dependencies
Fixes #85 
> chore(deps): add support for node 18

- .github/workflows/release.yml
releases will be via the workflow
GH-71
Added the release.yml file 
also added the necessary screts and variables at repo level
Fixes #71 
> chore(ci-cd): add the github release workflow

- .github/workflows/release.yml
add the git token for semantic release command 
Fixes #71
> chore(ci-cd): add the git token for semantic release commamd

- catalog-info.yaml
- docs/index.md
- mkdocs.yml
> Add Techdocs in backstage

- src/component.ts
- src/mixins/audit.mixin.ts
- src/mixins/conditional-audit.mixin.ts
- src/models/audit-log.model.ts
- src/types.ts
> refactor(chore): fix sonar code smells

- src/__tests__/acceptance/fixtures/models/audit.model.ts
- src/mixins/audit.mixin.ts
- src/models/audit-log.model.ts
add tenant provision in audit logs
BREAKING CHANGE:
add tenant provision in audit logs
Fixes #101 
> feat(chore): add tenant provision in audit logs

- src/__tests__/unit/audit.mixin.unit.ts
- src/types.ts
refactor user interface
gh-107
Fixes #107 
> fix(mixin): refactor user interface

- src/__tests__/acceptance/audit.mixin.acceptance.ts
- src/__tests__/unit/audit.mixin.unit.ts
- src/__tests__/unit/fixtures/mockData.ts
refactor test cases related to pr 108
gh-107
> fix(mixin): refactor test cases related to pr 108

- package-lock.json
- package.json
- src/__tests__/acceptance/audit.mixin.acceptance.ts
- src/__tests__/acceptance/fixtures/dummy-application.ts
- src/__tests__/acceptance/fixtures/helper/db.helper.ts
- src/__tests__/acceptance/fixtures/repositories/audit.repository.ts
- src/__tests__/acceptance/fixtures/repositories/test-error.repository.ts
- src/component.ts
- src/mixins/audit.mixin.ts
- src/models/audit-log.model.ts
- src/models/tenant-support/audit-log.model.ts
- src/models/tenant-support/index.ts
- src/repositories/audit.repository.ts
- src/repositories/sequelize/audit.repository.ts
enable multi tenant support
core changes that is related to this PR - https://github.com/sourcefuse/loopback4-microservice-catalog/pull/2063
> feat(mixin): enable multi tenant support

- .github/workflows/main.yml
- src/__tests__/acceptance/fixtures/dummy-application.ts
- src/mixins/audit.mixin.ts
test case update related to pr 103
gh-0
> fix(mixin): test case update related to pr 103

- .github/workflows/release.yml
- package.json
after release generate changelog
GH-118
add step to generate changelog
Fixes #118 
> fix(ci-cd): add step to generate changelog

- .github/workflows/release.yml
change the remote origin in release workflow
GH-118
rectify the remote origin
Fixes #118 
> fix(ci-cd): rectify the remote origin

- README.md
While trying an example with the way mentioned in the docs, I was facing an issue with changes to the repo for audit.
The error was as follows: 
```
Class 'InvoicesRepository' incorrectly extends base class 'DefaultCrudRepository<Invoices, number | undefined, InvoicesRelations> & IAuditMixin<string | number>'.
Type 'InvoicesRepository' is not assignable to type 'IAuditMixin<string | number>'.
The types returned by 'getAuditLogRepository()' are incompatible between these types.
Type 'Promise<AuditLogRepository>' is not assignable to type 'Promise<AuditLogRepository | AuditLogRepository>'.
Type 'AuditLogRepository' is not assignable to type 'AuditLogRepository | AuditLogRepository'.
Property 'auditLog' is missing in type
```
This is code for the repository that caused the issue:
```
import …
```
> chore(docs): update the readme file

- README.md
- docs/README.md
update the readme file in docs folder as well
GH-96
update the sonar and synk badges in README file
Fixes #96
> docs(chore): update the sonar and synk badges

- package-lock.json
- package.json
> chore(deps): core version update

- README.md
- docs/README.md
- package-lock.json
- src/mixins/audit.mixin.ts
dynamically pass extra values to add to audit log model
GH-141
dynamically pass extra values to add to audit log model
Fixes #141
> fix(mixin): pass the extra values via options
